[package]
name = "markdown"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
wasmtime-rust = { git = 'https://github.com/cranestation/wasmtime' }
anyhow = "1"
